name: Deploy AWS Glue ETL Jobs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Glue scripts to S3
        run: |
          aws s3 sync glue-job s3://steam-github-sync-bucket/glue-scripts/

      - name: Update Glue job with latest scripts
        run: |
          aws glue update-job --job-name reviews_silver_job \
            --job-update Command='{Name=glueetl,ScriptLocation=s3://steam-github-sync-bucket/glue-scripts/reviews_transformations.py}'

          aws glue update-job --job-name applications_silver_job \
            --job-update Command='{Name=glueetl,ScriptLocation=s3://steam-github-sync-bucket/glue-scripts/applications_transformations.py}'

          aws glue update-job --job-name dimensions_silver_job \
            --job-update Command='{Name=glueetl,ScriptLocation=s3://steam-github-sync-bucket/glue-scripts/join_bridges.py}'

          aws glue update-job --job-name gold_master_job \
            --job-update Command='{Name=glueetl,ScriptLocation=s3://steam-github-sync-bucket/glue-scripts/masterdata.py}'
          aws glue update-job --job-name gold_master_job \
            --job-update '{
              "Role": "AWSGlueServiceRoleDefault",
              "Command": {
                "Name": "glueetl",
                "ScriptLocation": "s3://steam-github-sync-bucket/glue-scripts/masterdata.py"
              }
            }'

